<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enums\Enums.csproj" />
    <ProjectReference Include="..\Everything.Data.Fake\Everything.Data.Fake.csproj" />
    <ProjectReference Include="..\Everything.Data.Interface\Everything.Data.Interface.csproj" />
    <ProjectReference Include="..\Everything.Data\Everything.Data.csproj" />
    <ProjectReference Include="..\LifeGame\LifeGame.csproj" />
    <ProjectReference Include="..\MazeCore\MazeCore.csproj" />
    <ProjectReference Include="..\SimulatorOfPrinting\SimulatorOfPrinting\SimulatorOfPrinting.csproj" />
    <ProjectReference Include="..\TagGame\TagGame.csproj" />
  </ItemGroup>



  <ItemGroup>
    <Folder Include="wwwroot\css\ServiceCenter\" />
    <Folder Include="wwwroot\images\avatars\" />
    <Folder Include="wwwroot\files\" />
    <Folder Include="wwwroot\images\Ecology\eccologyPosts\" />
    <Folder Include="wwwroot\images\LoadTesting\avatars\" />
    <Folder Include="wwwroot\images\LoadTesting\icon\" />
  </ItemGroup>



  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10-rc.2.24474.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10-rc.2.24474.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>



  <ItemGroup>
	  <Compile Update="Localizations\Cake.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Cake.resx</DependentUpon>
    </Compile>
	  <Compile Update="Localizations\Surveys.En.Designer.cs">
	    <DependentUpon>Surveys.En.resx</DependentUpon>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
	  <Compile Update="Localizations\Surveys.Designer.cs">
	    <DependentUpon>Surveys.resx</DependentUpon>
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	  </Compile>
    <Compile Update="Localizations\LoadStuffs.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LoadStuffs.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\LocalizationForGame\GameShop.Designer.cs">
		<DesignTime>True</DesignTime>
		<AutoGen>True</AutoGen>
		<DependentUpon>GameShop.resx</DependentUpon>
	</Compile>
    <Compile Update="Localizations\Coffe.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Coffe.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Girl.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Girl.resx</DependentUpon>
    </Compile>
	  <Compile Update="Localizations\Home.Designer.cs">
	  <DependentUpon>Home.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Localizations\LocalizationForGame\HomeGame.Designer.cs"></Compile>
    <Compile Update="Localizations\Home.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
	  <DependentUpon>HomeGame.resx</DependentUpon>
      <DependentUpon>Home.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\Ecology.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Ecology.resx</DependentUpon>
    </Compile>
    <Compile Update="Localizations\MoviePoster.En.Designer.cs">
      <DependentUpon>MoviePoster.En.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Localizations\MoviePoster.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MoviePoster.resx</DependentUpon>
    </Compile>
  </ItemGroup>



  <ItemGroup>
	  <EmbeddedResource Update="Localizations\Cake.En.resx">
		  <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\Cake.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>Cake.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\Surveys.En.resx">
	    <LastGenOutput>Surveys.En.Designer.cs</LastGenOutput>
	    <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\Surveys.resx">
	    <LastGenOutput>Surveys.Designer.cs</LastGenOutput>
	    <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\LoadStuffs.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>LoadStuffs.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\LoadStuffs.Ru.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\LocalizationForGame\GameShop.En.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\LocalizationForGame\GameShop.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		  <LastGenOutput>GameShop.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\LocalizationForGame\HomeGame.En.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
	  </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Coffe.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Coffe.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Girl.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Girl.Designer.cs</LastGenOutput>
    </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\Home.resx">
		  <LastGenOutput>Home.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Localizations\LocalizationForGame\HomeGame.resx"> </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Home.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
		<LastGenOutput>HomeGame.Designer.cs</LastGenOutput>
      <LastGenOutput>Home.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\Ecology.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Ecology.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\MoviePoster.En.resx">
      <LastGenOutput>MoviePoster.En.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizations\MoviePoster.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MoviePoster.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>



  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\css\Ecology\button.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\Ecology\chat.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\Ecology\dark-profile.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\Ecology\postCreation.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\Ecology\profile.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\Ecology\reset.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\Ecology\style.css" />
    <_ContentIncludedByDefault Remove="wwwroot\js\Ecology\chat.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\Ecology\index.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\Ecology\PostCreationForm.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\Ecology\theme.js" />
  </ItemGroup>


</Project>
