//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortalEverthing.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Surveys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Surveys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortalEverthing.Localizations.Surveys", typeof(Surveys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый документ.
        /// </summary>
        public static string Documents_Create_Name {
            get {
                return ResourceManager.GetString("Documents_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы.
        /// </summary>
        public static string Documents_Index_Name {
            get {
                return ResourceManager.GetString("Documents_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документов нет.
        /// </summary>
        public static string Documents_Index_Table_Empty {
            get {
                return ResourceManager.GetString("Documents_Index_Table_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Login_Name {
            get {
                return ResourceManager.GetString("Login_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация нового пользователя.
        /// </summary>
        public static string Register_Name {
            get {
                return ResourceManager.GetString("Register_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздел в разработке.
        /// </summary>
        public static string Section_Under_Development {
            get {
                return ResourceManager.GetString("Section_Under_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование группы.
        /// </summary>
        public static string SurveyGroup_Create_GroupName {
            get {
                return ResourceManager.GetString("SurveyGroup_Create_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание новой группы опросов.
        /// </summary>
        public static string SurveyGroup_Create_Name {
            get {
                return ResourceManager.GetString("SurveyGroup_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую группу.
        /// </summary>
        public static string SurveyGroup_Index_Create {
            get {
                return ResourceManager.GetString("SurveyGroup_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создал.
        /// </summary>
        public static string SurveyGroup_Index_Creator {
            get {
                return ResourceManager.GetString("SurveyGroup_Index_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы опросов.
        /// </summary>
        public static string SurveyGroup_Index_Name {
            get {
                return ResourceManager.GetString("SurveyGroup_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Surveys_HomePage {
            get {
                return ResourceManager.GetString("Surveys_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string Surveys_Index_Name {
            get {
                return ResourceManager.GetString("Surveys_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Surveys_Login {
            get {
                return ResourceManager.GetString("Surveys_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Surveys_Logout {
            get {
                return ResourceManager.GetString("Surveys_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы.
        /// </summary>
        public static string Surveys_Menu_Documents {
            get {
                return ResourceManager.GetString("Surveys_Menu_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        public static string Surveys_Menu_Statistics {
            get {
                return ResourceManager.GetString("Surveys_Menu_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы опросов.
        /// </summary>
        public static string Surveys_Menu_Survey_Groups {
            get {
                return ResourceManager.GetString("Surveys_Menu_Survey_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опросы.
        /// </summary>
        public static string Surveys_Menu_Surveys {
            get {
                return ResourceManager.GetString("Surveys_Menu_Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тесты.
        /// </summary>
        public static string Surveys_Menu_Tests {
            get {
                return ResourceManager.GetString("Surveys_Menu_Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string Surveys_Notification {
            get {
                return ResourceManager.GetString("Surveys_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль пользователя.
        /// </summary>
        public static string Surveys_Profile_Name {
            get {
                return ResourceManager.GetString("Surveys_Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегестироваться.
        /// </summary>
        public static string Surveys_Registration {
            get {
                return ResourceManager.GetString("Surveys_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сервис опросов и тестов.
        /// </summary>
        public static string Surveys_Site_Name {
            get {
                return ResourceManager.GetString("Surveys_Site_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разворачивать содержимое всех групп.
        /// </summary>
        public static string Surveys_SurveysAll_ExpandGroups {
            get {
                return ResourceManager.GetString("Surveys_SurveysAll_ExpandGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны опросов.
        /// </summary>
        public static string Surveys_SurveysAll_Name {
            get {
                return ResourceManager.GetString("Surveys_SurveysAll_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый опрос.
        /// </summary>
        public static string Surveys_SurveysAll_NewSurvey {
            get {
                return ResourceManager.GetString("Surveys_SurveysAll_NewSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Surveys_Users {
            get {
                return ResourceManager.GetString("Surveys_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string SurveysAdmin_Users_Name {
            get {
                return ResourceManager.GetString("SurveysAdmin_Users_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string SurveysAdmin_Users_Roles {
            get {
                return ResourceManager.GetString("SurveysAdmin_Users_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пройдено.
        /// </summary>
        public static string SurveyStatistics_Index_Completed {
            get {
                return ResourceManager.GetString("SurveyStatistics_Index_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процессе выполнения.
        /// </summary>
        public static string SurveyStatistics_Index_InProcess {
            get {
                return ResourceManager.GetString("SurveyStatistics_Index_InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика опросов.
        /// </summary>
        public static string SurveyStatistics_Index_Name {
            get {
                return ResourceManager.GetString("SurveyStatistics_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть ответы.
        /// </summary>
        public static string SurveyStatistics_Index_ViewAnswers {
            get {
                return ResourceManager.GetString("SurveyStatistics_Index_ViewAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты прохождения опроса.
        /// </summary>
        public static string SurveyStatistics_ViewAnswers_Name {
            get {
                return ResourceManager.GetString("SurveyStatistics_ViewAnswers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тесты.
        /// </summary>
        public static string SurveyTests_Index_Name {
            get {
                return ResourceManager.GetString("SurveyTests_Index_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросов нет.
        /// </summary>
        public static string TakingSurvey_Index_Table_Empty {
            get {
                return ResourceManager.GetString("TakingSurvey_Index_Table_Empty", resourceCulture);
            }
        }
    }
}
